fix(core): prevent duplicate dependency errors on customization
this change ensures that popper/index.scss isn't used multiple times when
a developer configures it using "with".
SassError: This module was already loaded, so it can't be configured using "with".