chore(react): set include to avoid overwrite error
if a dist build already existed, running the typescript build was throwing `error TS5055: Cannot write file because it would overwrite input file.` this resolves that.